require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.lualine")
require("user.colorscheme")
require("user.nvimtree")
require("user.cmp")
require("user.treesitter")
require("user.comment")
require("user.telescope")
require("user.lsp")
--[[ require("user.nullls") ]]
require("user.autopairs")
require("user.gitsigns")
require("user.dashboard")
require("user.autocmd")
require("user.toggleterm")
